#!/usr/bin/env python3
import os
import sys
import random

curdir = os.path.dirname(os.path.realpath(__file__))
with open(os.path.join(curdir, 'emoji-db')) as f:
    emoji = f.readlines()

with open(sys.argv[1]) as f:
    text = f.read()

with open(sys.argv[1], 'w') as f:
    f.write('{} :{}:'.format(text.strip(), random.choice(emoji).strip()))
