#!/usr/bin/env python3
import os
import sys
import yaml
import random


with open(os.path.join(sys.prefix, 'database.yml')) as f:
    emoji = yaml.load(f.read())

with open(sys.argv[1]) as f:
    text = f.read()

with open(sys.argv[1], 'w') as f:
    f.write('{} :{}:'.format(text.strip(), random.choice(emoji)))
